export default {
    /**
     * 主题
     */
    THEME_CHANGE: "THEME_CHANGE",
    THEME_INIT: "THEME_INIT",
    SHOW_THEME_VIEW: "SHOW_THEME_VIEW",
    /**
     * popular
     */
    POPULAR_REFRESH: "POPULAR_REFRESH",
    POPULAR_REFRESH_FAIL: "POPULAR_REFRESH_FAIL",
    POPULAR_REFRESH_SUCCESS: "POPULAR_REFRESH_SUCCESS",
    POPULAR_LOAD_MORE_SUCCESS: "POPULAR_LOAD_MORE_SUCCESS",
    POPULAR_LOAD_MORE_FAIL: "POPULAR_LOAD_MORE_FAIL",
    POPULAR_FLUSH_FAVORITE: 'POPULAR_FLUSH_FAVORITE',
    /**
     * trending
     */
    TRENDING_REFRESH: "TRENDING_REFRESH",
    TRENDING_REFRESH_FAIL: "TRENDING_REFRESH_FAIL",
    TRENDING_REFRESH_SUCCESS: "TRENDING_REFRESH_SUCCESS",
    TRENDING_LOAD_MORE_SUCCESS: "TRENDING_LOAD_MORE_SUCCESS",
    TRENDING_LOAD_MORE_FAIL: "TRENDING_LOAD_MORE_FAIL",
    TRENDING_FLUSH_FAVORITE: 'TRENDING_FLUSH_FAVORITE',
    /**
     * 收藏
     */
    FAVORITE_LOAD_DATA: 'FAVORITE_LOAD_DATA',
    FAVORITE_LOAD_SUCCESS: 'FAVORITE_LOAD_SUCCESS',
    FAVORITE_LOAD_FAIL: 'FAVORITE_LOAD_FAIL',
    /**
     * 自定义语言
     */
    LANGUAGE_LOAD_SUCCESS: "LANGUAGE_LOAD_SUCCESS",
    /**
     * 搜索
     */
    SEARCH_LOAD_MORE_SUCCESS: "SEARCH_LOAD_MORE_SUCCESS",
    SEARCH_LOAD_MORE_FAIL: "SEARCH_LOAD_MORE_FAIL",
    SEARCH_REFRESH: "SEARCH_REFRESH",
    SEARCH_CANCEL: "SEARCH_CANCEL",
    SEARCH_FAIL: "SEARCH_FAIL",
    SEARCH_REFRESH_SUCCESS: "SEARCH_REFRESH_SUCCESS",
}